### ISSUE TITLE
size不同多组的时候，上下移动事崩溃

### ISSUE THREAD

**Issue by Liyongcong** [liangdahong/BMLongPressDragCellCollectionView#10]
[self moveItemAtIndexPath:_oldIndexPath toIndexPath:_currentIndexPath];崩溃到这句

**Comment by liangdahong** [comment]
@Liyongcong  你好，是否可以提供Demo给我验证下。

**Comment by liangdahong** [comment]
@Liyongcong  已修复。请使用 https://github.com/liangdahong/BMDragCellCollectionView/releases/tag/2.0.3
