### ISSUE TITLE
/Users/yao/Downloads/BMDragCellCollectionView-master/BMDragCellCollectionViewDemo/BMDragCellCollectionViewDemo/Demo/BMImageVC/View/BMImageCell.xib: Compiling IB documents for earlier than iOS 7 is no longer supported.

### ISSUE THREAD

**Issue by Ya0HJ** [liangdahong/BMLongPressDragCellCollectionView#11]
/Users/yao/Downloads/BMDragCellCollectionView-master/BMDragCellCollectionViewDemo/BMDragCellCollectionViewDemo/Demo/BMImageVC/View/BMImageCell.xib: Compiling IB documents for earlier than iOS 7 is no longer supported.

**Comment by liangdahong** [comment]
@Ya0HJ  谢谢！ 是由于Demo的 Target 设置为6.0的问题，已处理哈。

**Comment by Ya0HJ** [comment]
点击今日头条(超过一屏)  进去了后的页面，点击cell的X号，没有反应。




------------------ 原始邮件 ------------------
发件人: "idhong";<notifications@github.com>;
发送时间: 2017年12月9日(星期六) 中午1:44
收件人: "asiosldh/BMDragCellCollectionView"<BMDragCellCollectionView@noreply.github.com>;
抄送: "༺✨卍✨༻"<497661841@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [asiosldh/BMDragCellCollectionView]/Users/yao/Downloads/BMDragCellCollectionView-master/BMDragCellCollectionViewDemo/BMDragCellCollectionViewDemo/Demo/BMImageVC/View/BMImageCell.xib:Compiling IB documents for earlier than iOS 7 is no longer supported. (#11)




@Ya0HJ  谢谢！ 是由于Demo的 Target 设置为6.0的问题，已处理哈。

**Comment by liangdahong** [comment]
@Ya0HJ  已修复 https://github.com/asiosldh/BMDragCellCollectionView/commit/27d49c46cffd0c73c5635bdfab75519a1f505554

**Comment by Ya0HJ** [comment]
O(∩_∩)O谢谢






------------------ 原始邮件 ------------------
发件人: "idhong";<notifications@github.com>;
发送时间: 2017年12月11日(星期一) 上午10:36
收件人: "asiosldh/BMDragCellCollectionView"<BMDragCellCollectionView@noreply.github.com>;
抄送: "༺✨卍✨༻"<497661841@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [asiosldh/BMDragCellCollectionView]/Users/yao/Downloads/BMDragCellCollectionView-master/BMDragCellCollectionViewDemo/BMDragCellCollectionViewDemo/Demo/BMImageVC/View/BMImageCell.xib:Compiling IB documents for earlier than iOS 7 is no longer supported. (#11)




@Ya0HJ  已修复 27d49c4

**Comment by Ya0HJ** [comment]
大神，可以把今日头条这块完善一下吗？比如添加cell或者删除cell后把值回调，然后根据回调的值创建控制器。最近在做一个项目，需求就是要做类似今日头条的频道这这样的。求完善。




------------------ 原始邮件 ------------------
发件人: "idhong";<notifications@github.com>;
发送时间: 2017年12月11日(星期一) 上午10:36
收件人: "asiosldh/BMDragCellCollectionView"<BMDragCellCollectionView@noreply.github.com>;
抄送: "༺✨卍✨༻"<497661841@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [asiosldh/BMDragCellCollectionView]/Users/yao/Downloads/BMDragCellCollectionView-master/BMDragCellCollectionViewDemo/BMDragCellCollectionViewDemo/Demo/BMImageVC/View/BMImageCell.xib:Compiling IB documents for earlier than iOS 7 is no longer supported. (#11)




@Ya0HJ  已修复 27d49c4

**Comment by liangdahong** [comment]
这个就是具体的业务了哦。 BMDragCellCollectionView 基本已提供此功能，这几天我尝试高仿下今日头条功能吧。

1、从界面VC跳到编辑界面(传入当前的的控制器数据)。
2、在编辑界面编辑完成后把修改后的值传回。
3、VC更新UI。

我不是大神哈😆

**Comment by Ya0HJ** [comment]
O(∩_∩)O谢谢，感激不尽！！！我可以加你微信吗？


------------------ 原始邮件 ------------------
发件人: "idhong";<notifications@github.com>;
发送时间: 2017年12月11日(星期一) 上午10:52
收件人: "asiosldh/BMDragCellCollectionView"<BMDragCellCollectionView@noreply.github.com>;
抄送: "༺✨卍✨༻"<497661841@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [asiosldh/BMDragCellCollectionView]/Users/yao/Downloads/BMDragCellCollectionView-master/BMDragCellCollectionViewDemo/BMDragCellCollectionViewDemo/Demo/BMImageVC/View/BMImageCell.xib:Compiling IB documents for earlier than iOS 7 is no longer supported. (#11)




这个就是具体的业务了哦。 BMDragCellCollectionView 基本已提供此功能，这几天我尝试高仿下今日头条功能吧。
 
1、从界面VC跳到编辑界面(传入当前的的控制器数据)。
 2、在编辑界面编辑完成后把修改后的值传回。
 3、VC更新UI。

**Comment by liangdahong** [comment]
@Ya0HJ  中午简单弄了下  https://github.com/asiosldh/ToutiaoDemo   代码随便撸的哈。
微信：liangdahong2014

**Comment by Ya0HJ** [comment]
感激不尽。但是缺少pod，跑不起来。


------------------ 原始邮件 ------------------
发件人: "idhong";<notifications@github.com>;
发送时间: 2017年12月11日(星期一) 下午2:35
收件人: "asiosldh/BMDragCellCollectionView"<BMDragCellCollectionView@noreply.github.com>;
抄送: "༺✨卍✨༻"<497661841@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [asiosldh/BMDragCellCollectionView]/Users/yao/Downloads/BMDragCellCollectionView-master/BMDragCellCollectionViewDemo/BMDragCellCollectionViewDemo/Demo/BMImageVC/View/BMImageCell.xib:Compiling IB documents for earlier than iOS 7 is no longer supported. (#11)




@Ya0HJ  中午简单弄了下  https://github.com/asiosldh/ToutiaoDemo   代码随便撸的哈。
 微信：liangdahong2014

**Comment by liangdahong** [comment]
https://github.com/asiosldh/ToutiaoDemo/commit/0594a6da2f866820cc026d2730ea770615e55a8d  已上传压缩包，建议使用 cocoapods

**Comment by Ya0HJ** [comment]
可以了。再次感谢。
------------------ 原始邮件 ------------------
发件人: "idhong";<notifications@github.com>;
发送时间: 2017年12月11日(星期一) 下午2:35
收件人: "asiosldh/BMDragCellCollectionView"<BMDragCellCollectionView@noreply.github.com>;
抄送: "༺✨卍✨༻"<497661841@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [asiosldh/BMDragCellCollectionView]/Users/yao/Downloads/BMDragCellCollectionView-master/BMDragCellCollectionViewDemo/BMDragCellCollectionViewDemo/Demo/BMImageVC/View/BMImageCell.xib:Compiling IB documents for earlier than iOS 7 is no longer supported. (#11)




@Ya0HJ  中午简单弄了下  https://github.com/asiosldh/ToutiaoDemo   代码随便撸的哈。
 微信：liangdahong2014

**Comment by Ya0HJ** [comment]
再提一个过分的要求哈。如果要把频道做成本地持久化的话，该怎么做呢？




------------------ 原始邮件 ------------------
发件人: "idhong";<notifications@github.com>;
发送时间: 2017年12月11日(星期一) 下午2:58
收件人: "asiosldh/BMDragCellCollectionView"<BMDragCellCollectionView@noreply.github.com>;
抄送: "༺✨卍✨༻"<497661841@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [asiosldh/BMDragCellCollectionView]/Users/yao/Downloads/BMDragCellCollectionView-master/BMDragCellCollectionViewDemo/BMDragCellCollectionViewDemo/Demo/BMImageVC/View/BMImageCell.xib:Compiling IB documents for earlier than iOS 7 is no longer supported. (#11)




asiosldh/ToutiaoDemo@0594a6d  已上传压缩包，建议使用 cocoapods

**Comment by liangdahong** [comment]
直接本地化或者 YYCache 、TMCache吧 😭

**Comment by Ya0HJ** [comment]
你好，我现在遇到一个问题。是有多个可添加标签组。这种情况该怎么做？






------------------ 原始邮件 ------------------
发件人: "idhong";<notifications@github.com>;
发送时间: 2017年12月11日(星期一) 晚上7:54
收件人: "asiosldh/BMDragCellCollectionView"<BMDragCellCollectionView@noreply.github.com>;
抄送: "༺✨卍✨༻"<497661841@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [asiosldh/BMDragCellCollectionView]/Users/yao/Downloads/BMDragCellCollectionView-master/BMDragCellCollectionViewDemo/BMDragCellCollectionViewDemo/Demo/BMImageVC/View/BMImageCell.xib:Compiling IB documents for earlier than iOS 7 is no longer supported. (#11)




直接本地化或者 YYCache 、TMCache吧 😭

**Comment by Ya0HJ** [comment]
大佬，大佬。对于toutiaodemo  我有个问题。如果我的频道是从网络获取的。我应该在哪里修改？跪求大佬解答。




------------------ 原始邮件 ------------------
发件人: "idhong";<notifications@github.com>;
发送时间: 2017年12月11日(星期一) 下午2:58
收件人: "asiosldh/BMDragCellCollectionView"<BMDragCellCollectionView@noreply.github.com>;
抄送: "༺✨卍✨༻"<497661841@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [asiosldh/BMDragCellCollectionView]/Users/yao/Downloads/BMDragCellCollectionView-master/BMDragCellCollectionViewDemo/BMDragCellCollectionViewDemo/Demo/BMImageVC/View/BMImageCell.xib:Compiling IB documents for earlier than iOS 7 is no longer supported. (#11)




asiosldh/ToutiaoDemo@0594a6d  已上传压缩包，建议使用 cocoapods

**Comment by liangdahong** [comment]
这个就是具体的业务需求了，一般流程是：

1、请求网络数据。
2、由请求到的数据进行UI刷新。
3、操作本地UI。
4、在把变更的UI数据发送到服务器。

仅供参考

**Comment by Ya0HJ** [comment]
好的。谢谢。




------------------ 原始邮件 ------------------
发件人: "idhong";<notifications@github.com>;
发送时间: 2018年1月29日(星期一) 上午8:35
收件人: "asiosldh/BMDragCellCollectionView"<BMDragCellCollectionView@noreply.github.com>;
抄送: "༺✨卍✨༻"<497661841@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [asiosldh/BMDragCellCollectionView]/Users/yao/Downloads/BMDragCellCollectionView-master/BMDragCellCollectionViewDemo/BMDragCellCollectionViewDemo/Demo/BMImageVC/View/BMImageCell.xib:Compiling IB documents for earlier than iOS 7 is no longer supported. (#11)




这个就是具体的业务需求了，一般流程是：
 
1、请求网络数据。
 2、由请求到的数据进行UI刷新。
 3、操作本地UI。
 4、在把变更的UI数据发送到服务器。
 
仅供参考

**Comment by Ya0HJ** [comment]
大佬，大佬。请问把加号移到下面的频道view的最右边，应该怎么做？求指教。感激不尽！！！




------------------ 原始邮件 ------------------
发件人: "idhong";<notifications@github.com>;
发送时间: 2017年12月11日(星期一) 下午2:58
收件人: "asiosldh/BMDragCellCollectionView"<BMDragCellCollectionView@noreply.github.com>;
抄送: "༺✨卍✨༻"<497661841@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [asiosldh/BMDragCellCollectionView]/Users/yao/Downloads/BMDragCellCollectionView-master/BMDragCellCollectionViewDemo/BMDragCellCollectionViewDemo/Demo/BMImageVC/View/BMImageCell.xib:Compiling IB documents for earlier than iOS 7 is no longer supported. (#11)




asiosldh/ToutiaoDemo@0594a6d  已上传压缩包，建议使用 cocoapods

**Comment by liangdahong** [comment]
@Ya0HJ  ？不懂

**Comment by Ya0HJ** [comment]
我已经弄好了。感谢！！！




------------------ 原始邮件 ------------------
发件人: "idhong";<notifications@github.com>;
发送时间: 2018年2月9日(星期五) 中午11:42
收件人: "asiosldh/BMDragCellCollectionView"<BMDragCellCollectionView@noreply.github.com>;
抄送: "༺✨卍✨༻"<497661841@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [asiosldh/BMDragCellCollectionView]/Users/yao/Downloads/BMDragCellCollectionView-master/BMDragCellCollectionViewDemo/BMDragCellCollectionViewDemo/Demo/BMImageVC/View/BMImageCell.xib:Compiling IB documents for earlier than iOS 7 is no longer supported. (#11)




@Ya0HJ  ？不懂
