### ISSUE TITLE
使用的时候会发现BMDragCellCollectionView 有重用问题，本来有7张图片，拖拽过后，会变6张，然后划回去，不见的那一张又自己出现了

### ISSUE THREAD

**Issue by IIIOS** [liangdahong/BMLongPressDragCellCollectionView#14]
楼主加我qq  （423824864），求助啊，急急急，

**Comment by liangdahong** [comment]
麻烦提供 Demo 和 步骤给我，我调试下看看。 
@IIIOS   谢谢！

**Comment by IIIOS** [comment]
兄弟，加我qq好交流点。谢谢了




------------------ 原始邮件 ------------------
发件人: "liangdahong"<notifications@github.com>;
发送时间: 2018年5月17日(星期四) 上午9:15
收件人: "liangdahong/BMDragCellCollectionView"<BMDragCellCollectionView@noreply.github.com>;
抄送: "423824864"<423824864@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [liangdahong/BMDragCellCollectionView] 使用的时候会发现BMDragCellCollectionView 有重用问题，本来有7张图片，拖拽过后，会变6张，然后划回去，不见的那一张又自己出现了 (#14)




麻烦提供 Demo 和 步骤给我，我调试下看看。
 @IIIOS   谢谢！

**Comment by IIIOS** [comment]
本来录了个视频，发送给你的时候被退回来了，说不支持，能不能加我qq啊，好交流点




------------------ 原始邮件 ------------------
发件人: "liangdahong"<notifications@github.com>;
发送时间: 2018年5月17日(星期四) 上午9:15
收件人: "liangdahong/BMDragCellCollectionView"<BMDragCellCollectionView@noreply.github.com>;
抄送: "423824864"<423824864@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [liangdahong/BMDragCellCollectionView] 使用的时候会发现BMDragCellCollectionView 有重用问题，本来有7张图片，拖拽过后，会变6张，然后划回去，不见的那一张又自己出现了 (#14)




麻烦提供 Demo 和 步骤给我，我调试下看看。
 @IIIOS   谢谢！

**Comment by IIIOS** [comment]
qq 423824864

**Comment by IIIOS** [comment]
在线等啊555555555555555

**Comment by IIIOS** [comment]
自定义的cell : http://h.pz.com/u/7633/122/1/152652114939.png

使用自定义的cell:http://h.pz.com/u/7633/122/2/152652120213.png

没搞懂为啥会重用

**Comment by liangdahong** [comment]
@IIIOS  问题已修复。 https://github.com/liangdahong/BMDragCellCollectionView/releases/tag/2.0.2  
感谢！
