### ISSUE TITLE
严重bug:拖拽动画开始出现错误

### ISSUE THREAD

**Issue by WangFour** [liangdahong/BMLongPressDragCellCollectionView#15]
当cell满屏或者超过一屏幕时，长按当前屏幕最下面一行的cell，动画开始是会闪动，直接往上弹了一下，

**Comment by WangFour** [comment]
不只是最后一行，只要cell是处于边缘的cell，并且未显示完全时，长按之后都会跳动，

**Comment by liangdahong** [comment]
@WangFour  谢谢，我抽空处理下。

**Comment by WangFour** [comment]
我自己稍微处理了下，你边缘滚动timer不要在手势启动的时候添加就行了，在手势拖动的时候添加就可以了
case UIGestureRecognizerStateChanged: {
            
            if (self.delegate && [self.delegate respondsToSelector:@selector(dragCollectionView:changedDragAtPoint:indexPath:)]) {
                [self.delegate dragCollectionView:self changedDragAtPoint:point indexPath:indexPath];
            }
            
            if (!_edgeTimer) {
                [self _setEdgeTimer];
            }

只是暂时的处理

**Comment by WangFour** [comment]
我最近在做一个跟Teambition应用任务拖拽模块功能的交互设计，借鉴您的代码，你要是有兴趣可以去看下那个交互，希望有机会一起探讨下

**Comment by liangdahong** [comment]
@WangFour 非常感谢，好的，有机会一起探讨下！😁
