### ISSUE TITLE
空余的位置不会自动补全啊

### ISSUE THREAD

**Issue by JLLJHD** [liangdahong/BMLongPressDragCellCollectionView#17]

**Comment by liangdahong** [comment]
@JLLJHD  什么意思？ 😁

**Comment by JLLJHD** [comment]
@liangdahong 就是我移动不同的size的时候  移动大的size位置后 有空余出的地方是可以放下小一点的size的 但是目前是空出来的   还不明白我的意思的话可以加QQ 聊一下吗   327116244

**Comment by liangdahong** [comment]
请问是不同组之间的移动吗？
@JLLJHD

**Comment by JLLJHD** [comment]
相同的组之间

**Comment by liangdahong** [comment]
@JLLJHD  弄个 gif 我看看

**Comment by JLLJHD** [comment]
![simulator screen shot - iphone x - 2018-06-11 at 15 13 02](https://user-images.githubusercontent.com/18045759/41217285-02a67a32-6d8a-11e8-86d7-40c2e4fdd8d5.png)
你看 8和7之间就空了一个空白区域

**Comment by liangdahong** [comment]
8 个 7 之间后应该放 6  ，但 6 是放不下的、所以换行。

**Comment by JLLJHD** [comment]
但是9和10可以放下啊

**Comment by liangdahong** [comment]
(⊙_⊙)? 录 gif 我看看。

**Comment by JLLJHD** [comment]
这样设计也没错 也说的过去  就这样吧  哈哈哈

**Comment by liangdahong** [comment]
😭好
