### ISSUE TITLE
Could not find remote branch 1.1.4 to clone

### ISSUE THREAD

**Issue by yingongzheng123** [liangdahong/BMLongPressDragCellCollectionView#19]
Error installing BMDragCellCollectionView
[!] /usr/bin/git clone https://github.com/asiosldh/BMDragCellCollectionView.git /var/folders/fy/mg_fqbvx7xq7__63tfqpk4km0000gp/T/d20190527-8491-mhij39 --template= --single-branch --depth 1 --branch 1.1.4

Cloning into '/var/folders/fy/mg_fqbvx7xq7__63tfqpk4km0000gp/T/d20190527-8491-mhij39'...
warning: Could not find remote branch 1.1.4 to clone.
fatal: Remote branch 1.1.4 not found in upstream origin

**Comment by liangdahong** [comment]
请直接拖入项目使用，不要使用 pod 的方式导入。
@yingongzheng123

**Comment by yingongzheng123** [comment]
3Q
