### ISSUE TITLE
哥，pod install不了啊，是不是忘记推到cocoapos上了。。

### ISSUE THREAD

**Issue by cjsliuj** [liangdahong/BMLongPressDragCellCollectionView#22]

**Comment by liangdahong** [comment]
推了啊，你可以 `pod search   BMLongPressDragCellCollectionView` 到吗 ？

**Comment by liangdahong** [comment]
![image](https://user-images.githubusercontent.com/12118567/72357576-26f38580-3726-11ea-93a5-9ade1a332ba1.png)

![image](https://user-images.githubusercontent.com/12118567/72357513-0e836b00-3726-11ea-8c06-116cc01f8ed9.png)

@cjsliuj

**Comment by cjsliuj** [comment]
不好意思，我们项目配置问题。

**Comment by cjsliuj** [comment]
我有个疑问，这个库要求是9.0，但是我deploy target 8.0也能编译过呢，是哪些地方有不兼容？

**Comment by liangdahong** [comment]
@cjsliuj 代码是支持 7.0 以上哈，我调整下库 😂。
