### ISSUE TITLE
scrollDirection 一直为BMLongPressDragCellCollectionViewScrollDirectionNone

### ISSUE THREAD

**Issue by YuzuWang** [liangdahong/BMLongPressDragCellCollectionView#24]
你好，在使用的时候，scrollDirection 一直为BMLongPressDragCellCollectionViewScrollDirectionNone，导致不会调用拖拽结束的方法

**Comment by liangdahong** [comment]
@YuzuWang 
请问是在什么情况下呢 ？如何重现。

**Comment by YuzuWang** [comment]
我用你这个demo 跑也是这样的，支付宝拖动的那个，在 BMAlipayVC.m中添加
- (void)dragCellCollectionViewShouldEndExchange:(BMLongPressDragCellCollectionView *)dragCellCollectionView sourceIndexPath:(NSIndexPath *)sourceIndexPath toIndexPath:(NSIndexPath *)destinationIndexPath  代理方法，拖动结束了以后也没有调用，是我使用的有问题吗？

**Comment by liangdahong** [comment]
OK  我瞧瞧，谢谢反馈。

**Comment by liangdahong** [comment]
@YuzuWang  https://github.com/liangdahong/BMLongPressDragCellCollectionView/releases/tag/3.0.9 已处理，感谢反馈。

**Comment by liangdahong** [comment]
😃如果没有其他问题的话我关闭 issues 了哈，有任何问题可能随时沟通。
