### ISSUE TITLE
内存不释放

### ISSUE THREAD

**Issue by chennyhuang** [liangdahong/BMLongPressDragCellCollectionView#26]
用这个框架之后，pop控制器后，控制器不走delloc方法，必须手动 BMLongPressDragCellCollectionView removeFromSuperView 
BMLongPressDragCellCollectionView = nil 才行

**Comment by liangdahong** [comment]
有 Demo  吗 ？我使用框架自带的 demo 运行时没有出现无法释放的问题。
![image](https://user-images.githubusercontent.com/12118567/84127507-f49a4a00-aa71-11ea-81fe-c7516ebcb750.png)

**Comment by liangdahong** [comment]
@chennyhuang  可以尝试集成 https://github.com/liangdahong/AMLeaksFinder 同时导入  FBRetainCycleDetector 看看强引用链。

**Comment by chennyhuang** [comment]
不好意思，是我自己循环引用了导致没释放

**Comment by liangdahong** [comment]
哦哦，原来如此。😂
