### ISSUE TITLE
请问如何在交换数据后 使用reloadData?

### ISSUE THREAD

**Issue by FaDeve** [liangdahong/BMLongPressDragCellCollectionView#28]
我看现在作者用 banReload 拦截了

**Comment by liangdahong** [comment]
交换后为什么要 reloadData ？是有其他需求吗 ？

**Comment by FaDeve** [comment]
我目前的需求需要刷新整个数据

**Comment by FaDeve** [comment]
我发现在结束时调用 reloadData 只会刷新交换的cell?而不会刷新整个数据

**Comment by liangdahong** [comment]
哦哦，拦截只会在 cell 交换时拦截，因为交换时外面的使用者不应该 reloadData，你可以在 

```objc
/// 结束交换时
/// @param dragCellCollectionView dragCellCollectionView
/// @param sourceIndexPath 原来的 IndexPath
/// @param destinationIndexPath 被交换的 IndexPath
- (void)dragCellCollectionViewShouldEndExchange:(__kindof BMLongPressDragCellCollectionView *)dragCellCollectionView sourceIndexPath:(NSIndexPath *)sourceIndexPath toIndexPath:(NSIndexPath *)destinationIndexPath;
```
触发你的  reloadData ,

如果你必须想在 
```OBJC
/**
 Cell 有交换时调用
 
 @param dragCellCollectionView dragCellCollectionView
 @param newDataArray 最新的数据源，需要使用者保存，在拖拽的时候 Cell 已经移动，需保存最新的数据源

 - (void)dragCellCollectionView:(BMLongPressDragCellCollectionView *)dragCellCollectionView newDataArrayAfterMove:(nullable NSArray *)newDataArray {
    self.dataArray = [newDataArray copy];
 }
 */
- (void)dragCellCollectionView:(__kindof BMLongPressDragCellCollectionView *)dragCellCollectionView newDataArrayAfterMove:(nullable NSArray *)newDataArray;
```
触发 reloadDatad 的话你可以使用 async 来实现，但是不建议你这样做。

**Comment by liangdahong** [comment]
至于为什么要做这个拦截我后面在补充。

**Comment by FaDeve** [comment]
我现在就是在 - (void)dragCellCollectionViewShouldEndExchange:(__kindof BMLongPressDragCellCollectionView *)dragCellCollectionView sourceIndexPath:(NSIndexPath *)sourceIndexPath toIndexPath:(NSIndexPath *)destinationIndexPath;  这里触发 reloadData  但是发现只会刷新交换的(假设现在有四个数据,是会刷新一个,剩下的没发生变化),很奇怪

**Comment by liangdahong** [comment]
有 demo  吗 ？ 我晚上看看。

**Comment by FaDeve** [comment]
就在你demo那个 Alipay改造一下,每个cell加个index显示,交换之后重新排序.刚刚在你的demo试了下,也是同样情况,你可以看看

**Comment by liangdahong** [comment]
重新排序是什么意思？交换完成后你在改变数据源的排序情况，在 reloadtata 吗？

**Comment by liangdahong** [comment]
交换完后你的数据源已经同步调整了哦

**Comment by FaDeve** [comment]
<img width="550" alt="截屏2020-11-30 14 21 10" src="https://user-images.githubusercontent.com/13104291/100575543-5055d980-3317-11eb-86de-bbb9c6476a65.png">
数据源是同步调整了,比如我想把充值中心跟转账交换,那对应的数字也要重新排序.但发现调用reloadData,只会刷新一个,而不是整体

**Comment by FaDeve** [comment]
我刚刚实际上reloadData是起作用的,但是得在拖动的时候停一下,再放下去,这时候数据就整体刷新了.如果正常一拖动就放,就还是老数据,你可以试试

**Comment by FaDeve** [comment]
我刚刚发现实际上reloadData是起作用的,但是得在拖动的时候停一下,再放下去,这时候数据就整体刷新了.如果正常一拖动就放,就还是老数据,你可以试试

**Comment by FaDeve** [comment]
刚刚调试了一下,发现延迟0.25再刷新就正常了,猜测应该跟拖动时生成的图片做动画有影响

**Comment by liangdahong** [comment]
哦哦，你详细描述下你想要的需求，然后你的实现思路，然后遇到的问题，我晚一点看看，晚上下班了瞧瞧。

**Comment by liangdahong** [comment]
找到原因了，是因为正在移动 cell 的动画中，系统的如下方法：
```OBJC
- (void)moveItemAtIndexPath:(NSIndexPath *)indexPath toIndexPath:(NSIndexPath *)newIndexPath;
```
如果在移动时调用 reloadData 是不起作用的，估计是系统做了拦截，你可以写一个最简单的 demo 验证【就是系统的  UICollectionView 】，点击按钮触发如下的代码：

```OBJC
    [self.dataSourceArray exchangeObjectAtIndex:0 withObjectAtIndex:1];
    [self.dragCellCollectionView moveItemAtIndexPath:[NSIndexPath indexPathForItem:0 inSection:0] toIndexPath:[NSIndexPath indexPathForItem:1 inSection:0]];
    [self.dragCellCollectionView reloadData];
```

就会导致 reloadData 直接无效。

@FaDeve

**Comment by liangdahong** [comment]
你可以考虑换一种思路来实现，交换一下就触发 reloadData 是不怎么推荐的做法，可以考虑在
```OBJC
/// 结束拖拽时
/// @param dragCellCollectionView dragCellCollectionView
/// @param point 手指触摸点对于 collectionView 的位置
/// 可以参考 https://github.com/liangdahong/ToutiaoDemo/blob/master/ToutiaoDemo/Classes/Edit/Controller/BMChannelEditVC.m 的使用
- (void)dragCellCollectionView:(__kindof BMLongPressDragCellCollectionView *)dragCellCollectionView endedDragAtPoint:(CGPoint)point;
```

中才处理，但也要注意移动动画可能还没结束的问题，可以考虑暂时用延时来处理。

**Comment by FaDeve** [comment]
是的,我现在就是这样处理的,而且只能在这个方法,感谢回复

**Comment by liangdahong** [comment]
不客气。
