### ISSUE TITLE
can't find when useing the cocoapods

### ISSUE THREAD

**Issue by sa124a** [liangdahong/BMLongPressDragCellCollectionView#3]
Unable to find a specification for `BMDragCellCollectionView`

**Comment by liangdahong** [comment]
@sa124a please refer to the https://github.com/liangdahong/BMLongPressDragCellCollectionView thanks！

**Comment by zejun-huang** [comment]
请问支付宝的大约是什么时候完成呢？我想参考参考您的。

**Comment by liangdahong** [comment]
不好意思哈、最近有一点忙、没怎么弄、这周末写一下吧！

**Comment by liangdahong** [comment]
@HuangZejun0708 您好，支付宝类似的核心拖拽已基本完成，至于具体的业务逻辑可能暂时没时间添加，因为那已经是业务了，有时间可能会高仿下。

https://user-images.githubusercontent.com/12118567/89103527-18ac5300-d445-11ea-9d33-9581e1cde40d.gif

**Comment by zejun-huang** [comment]
您好，之前旧版的支付宝是拖拽的，现在新版的支付宝变化了。之前写过拖拽的，现在不能再用了。

**Comment by liangdahong** [comment]
@HuangZejun0708 对，是支付宝改了需求，有什么问题嘛？

**Comment by zejun-huang** [comment]
嗯，解决了，用了你的代码，很好的解决了我的问题。谢谢。非常之感谢。已经star

**Comment by idhong** [comment]
@HuangZejun0708 不客气哈。

**Comment by liangdahong** [comment]
@HuangZejun0708  不客气哈
