### ISSUE TITLE
collectionView自动滚动动画

### ISSUE THREAD

**Issue by ghost** [liangdahong/BMLongPressDragCellCollectionView#33]
复现步骤: 单分区情况，Alipay1数据源创建几十个，cell高度超过屏幕高度，定时器自动滚动的动画问题。
多分区Demo演示无此问题。

**Comment by liangdahong** [comment]
@Geng1122 我排查了下是因为 `dragSpeed` 设置太大导致的（Demo 在 xib 中设置为了 44 😄 ）, 使用默认值就没问题了，感谢。
```SWIFT
/// 拖拽到 UICollectionView 边缘时 UICollectionView 的滚动速度
/// 默认为: 8.0f ，建议设置 5.0f 到 15.0f 之间。
@property (nonatomic, assign) IBInspectable CGFloat dragSpeed;
```
![image](https://user-images.githubusercontent.com/12118567/119534286-50f89580-bdb9-11eb-82b7-2b41bc83e68b.png)

**Comment by ghost** [comment]
谢谢！更改了拖拽速度已正常。
