### ISSUE TITLE
size相同，多组，这个demo 如果有个组移完了，为什么不能重新往里面移动添加了啊

### ISSUE THREAD

**Issue by zhilong2005** [liangdahong/BMLongPressDragCellCollectionView#5]
size相同，多组，这个demo 如果有个组移完了，为什么不能重新往里面移动添加了啊

**Comment by liangdahong** [comment]
@zhilong2005 暂时没考虑这种情况，因为这样的需求似乎很少见，请问这方面的需求吗？以后可能考虑增加

**Comment by mistak1992** [comment]
恩, 确实会需要这个需求, 希望作者能加入这个功能

**Comment by liangdahong** [comment]
@zhilong2005  @mistak1992 👌有时间增加吧，增加了通知您哈。

**Comment by geekGetup** [comment]
size相同，多组，这个demo 如果有个组移完了，为什么不能重新往里面移动添加了啊

**Comment by JC-Passerby** [comment]
size相同，多组，这个demo 如果有个组移完了，为什么不能重新往里面移动添加了啊 @liangdahong

**Comment by liangdahong** [comment]
😂
这个功能目前没想好思路，有大佬贡献下吗 ？

@JC-Passerby @geekGetup @zhilong2005 @mistak1992

**Comment by chd123456** [comment]
是啊，我们现在也遇到了这种需求。

**Comment by liangdahong** [comment]
@chd123456 
已增加此功能，请使用最新代码查看。
![3](https://user-images.githubusercontent.com/12118567/64005374-ddbde300-cb42-11e9-8030-185c44c4f289.gif)

**Comment by liangdahong** [comment]
@JC-Passerby @geekGetup @zhilong2005 @mistak1992 

已增加此功能，请使用最新代码查看。
😁
